'use strict'

const mongoose = require('mongoose')

const assessmentSchema = new mongoose.Schema(
  {
    patient : { type: mongoose.Schema.Types.ObjectId, ref: 'Patient', required: true },
    doctor  : { type: mongoose.Schema.Types.ObjectId, ref: 'Doctor' },
    type    : { type: String, enum: ['clinical', 'ayush'], default: 'clinical' },
    language: { type: String, enum: ['en', 'ta', 'hi', 'te', 'kn', 'ml'], default: 'en' },
    status  : {
      type   : String,
      enum   : ['in-progress', 'completed', 'reviewed', 'approved'],
      default: 'in-progress',
    },
    consentGiven : { type: Boolean, default: false },

    // AI Interview
    interviewTranscript: [
      {
        role   : { type: String, enum: ['ai', 'patient'] },
        message: String,
        timestamp: { type: Date, default: Date.now },
      },
    ],
    symptoms     : [String],
    redFlags     : [String],
    urgencyLevel : { type: String, enum: ['low', 'medium', 'high', 'critical'], default: 'low' },

    // Clinical Summary (generated by AI)
    clinicalSummary : { type: String },
    medicalTimeline : [
      {
        date       : Date,
        event      : String,
        description: String,
      },
    ],

    // AYUSH fields
    ayush: {
      prakriti: { type: Object },
      vikriti : { type: Object },
      agni    : String,
      koshtha : String,
    },

    // Doctor review
    doctorNotes    : { type: String },
    reviewedAt     : { type: Date },
    approvedAt     : { type: Date },
  },
  { timestamps: true },
)

module.exports = mongoose.model('Assessment', assessmentSchema)
